\connect "db_shop";

DROP TABLE IF EXISTS "category";
CREATE TABLE "public"."category" (
                                     "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     "name" character varying(255),
                                     CONSTRAINT "category_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "category" ("id", "name") VALUES
                                          (0, 'Футболки'),
                                          (1, 'Рубашки');

DROP TABLE IF EXISTS "image";
CREATE TABLE "public"."image" (
                                  "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  "file_name" character varying(255),
                                  "product_id" integer NOT NULL,
                                  CONSTRAINT "image_pkey" PRIMARY KEY ("id"),
                                  CONSTRAINT "fkgpextbyee3uk9u6o2381m7ft1" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE
) WITH (oids = false);

INSERT INTO "image" ("id", "file_name", "product_id") VALUES
                                                          (35,  '216848.2000.jpg',  14),
                                                          (36,  'images.jfif',  14),
                                                          (37,  '0181Q-07X-001-1-464271_4.jpg', 15),
                                                          (38,  '0181Q-07X-003-1-464271_4.webp',  15),
                                                          (39,  'zelenyiy-big-1776x2664-f8b0.jpg',  16),
                                                          (40,  'zelenyiy-big-1776x2664-cbf4.jpg',  16),
                                                          (41,  'zelenyiy-big-1776x2664-c587.jpg',  16);

DROP TABLE IF EXISTS "orders";
CREATE TABLE "public"."orders" (
                                   "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "count" integer NOT NULL,
                                   "date_time" timestamp,
                                   "number" character varying(255),
                                   "price" real NOT NULL,
                                   "status" integer,
                                   "person_id" integer NOT NULL,
                                   "product_id" integer NOT NULL,
                                   CONSTRAINT "orders_pkey" PRIMARY KEY ("id"),
                                   CONSTRAINT "fk1b0m4muwx1t377w9if3w6wwqn" FOREIGN KEY (person_id) REFERENCES person(id) NOT DEFERRABLE,
                                   CONSTRAINT "fk787ibr3guwp6xobrpbofnv7le" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE
) WITH (oids = false);

INSERT INTO "orders" ("id", "count", "date_time", "number", "price", "status", "person_id", "product_id") VALUES
    (2, 1,  '2022-12-11 19:31:58.921395', 'a785f448-7eaa-48c8-b963-4ecb6edd8c2b', 1000, 1,  2,  14);

DROP TABLE IF EXISTS "person";
CREATE TABLE "public"."person" (
                                   "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "login" character varying(50),
                                   "password" character varying(255),
                                   "role" character varying(255),
                                   CONSTRAINT "person_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "person" ("id", "login", "password", "role") VALUES
                                                             (1, 'Admin',  '$2a$10$6wLmHA0SxiDBLY42GZq1EePk4faO9TsdyT.ViDgBsoDMEnKQdVUMW', 'ROLE_ADMIN'),
                                                             (2, 'Userr',  '$2a$10$OpQaNRMOlNQznegYsqpZ.u1EoJ3d6PIEVIrq3fpqrLIWWPst70T6i', 'ROLE_USER');

DROP TABLE IF EXISTS "product";
CREATE TABLE "public"."product" (
                                    "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "date_time_of_created" timestamp,
                                    "description" text NOT NULL,
                                    "price" real NOT NULL,
                                    "seller" character varying(255) NOT NULL,
                                    "title" text NOT NULL,
                                    "warehouse" character varying(255) NOT NULL,
                                    "category_id" integer NOT NULL,
                                    CONSTRAINT "product_pkey" PRIMARY KEY ("id"),
                                    CONSTRAINT "uk_qka6vxqdy1dprtqnx9trdd47c" UNIQUE ("title"),
                                    CONSTRAINT "fk1mtsbur82frn64de7balymq9s" FOREIGN KEY (category_id) REFERENCES category(id) NOT DEFERRABLE
) WITH (oids = false);

INSERT INTO "product" ("id", "date_time_of_created", "description", "price", "seller", "title", "warehouse", "category_id") VALUES
                                                                                                                                (14,  '2022-12-11 19:12:50.308681', 'Описание ',  1000, 'Григорий', 'Футболка мужская', 'Основной', 0),
                                                                                                                                (15,  '2022-12-11 19:14:14.01682',  'Описание', 1500, 'Григорий', 'Футболка женская', 'Основной', 0),
                                                                                                                                (16,  '2022-12-11 19:37:30.83049',  'Описание', 3000, 'Григорий', 'Рубашка женская',  'Основной', 1);

DROP TABLE IF EXISTS "product_cart";
CREATE TABLE "public"."product_cart" (
                                         "id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         "person_id" integer,
                                         "product_id" integer,
                                         CONSTRAINT "product_cart_pkey" PRIMARY KEY ("id"),
                                         CONSTRAINT "fkhpnrxdy3jhujameyod08ilvvw" FOREIGN KEY (product_id) REFERENCES product(id) NOT DEFERRABLE,
                                         CONSTRAINT "fksgnkc1ko2i1o9yr2p63ysq3rn" FOREIGN KEY (person_id) REFERENCES person(id) NOT DEFERRABLE
) WITH (oids = false);